### PR TITLE
Enhance logging in plcontainer

### PR DESCRIPTION
**Pull request by paul-guo-**
Use plc_elog() instead of elog() so that we could have seperate logging control than gpdb in the future.
Replace debug_print() with more meaningful function name channel_elog().
Replace all lprintf() with more meaning name plc_elog() also.

### CODE REVIEW

**Comment by paul-guo-** [comment]
@zhangh43 @HaozhouWang

**Comment by paul-guo-** [comment]
rclient code change will be added after the change enters.

**Comment by zhangh43** [comment]
plc_elog will add prefix on QE side, how about client side?

**Comment by paul-guo-** [comment]
@zhangh43  See common/comm_utils.h
```
#define plc_elog(lvl, fmt, ...)                                          \
        do {                                                            \
            FILE *out = stdout;                                         \
            if (lvl >= ERROR) {                                         \
                out = stderr;                                           \
            }                                                           \
            fprintf(out, "plcontainer log: %s, ", clientLanguage);      \
            fprintf(out, "%s, %s, %d, ", dbUsername, dbName, dbQePid);  \
            fprintf(out, #lvl ": ");                                    \
            fprintf(out, fmt, ##__VA_ARGS__);                           \
            fprintf(out, "\n");                                         \
            fflush(out);                                                \
            if (lvl >= ERROR) {                                         \
                exit(1);                                                \
            }                                                           \
        } while (0)

```

**Comment by zhangh43** [comment]
+1

**Pull request merged**
